CREATE OR REPLACE VIEW IROJAS941.ZACTJOB AS
SELECT JOB_NAME, SUBSYSTEM, JOB_STATUS, FUNCTION, RUN_PRIORITY, CPU_TIME, TOTAL_RUN_TIME
FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) X
WHERE AUTHORIZATION_NAME = 'IROJAS94';
