CREATE OR REPLACE TABLE IROJAS941.ZTEST (
  COL1 FOR COLUMN C1 VARCHAR(20) NOT NULL,
  COL2 FOR COLUMN C2 DECIMAL(18 , 2) NOT NULL DEFAULT 0,
  COL3 FOR COLUMN C3 DECIMAL(18) NOT NULL DEFAULT 0
) RCDFMT ZTESTR;
